Added default value option to ConfigurationListElement
SmartGridready/SGrSpecifications pull request #286
Opened 2024-05-13 08:19 UTC by mkrebs81

Modified the XML schema to accept default values.
Also updated the ABB B23 specification with configuration parameters.

Requires modification of SGrJava implementation in order to work.

2024-05-13 11:49 UTC, mkrebs81 commented
also added serial port name to Modbus RTU parameters

2024-05-13 11:58 UTC, ergo-furrer commented
> also added serial port name to Modbus RTU parameters

Hi @mkrebs81. Thanks for that!  

I recently encountered the same problem while implementing the SGr-Intermediary  in Java since it was not possible to handle the COM-Port the same way as the other properties.

2024-05-13 11:59 UTC, ArndGerns requested changes

2024-05-13 11:59 UTC, ArndGerns commented on SchemaDatabase/SGr/Product/Product.xsd
> +      <element name="defaultValue" type="string" />
I'ld make the defaultValue optional with `minOccurs="0"`. Then you don't need to define it everywhere.

2024-05-13 12:13 UTC, mkrebs81 commented
> Hi @ergo-furrer, @mkrebs81,
> 
> If we add the serial port, then some of the EID's are not valid any more.
> 
> Is there always a COM port? Then we need to update the existing EID's.
> 
> And what is that in `mvpEi4Modbus_0000_0036_0030_4_0.1_SGCP_BiDirFlexMgmt.xml`:
> 
> ```
>       <modbusInterfaceDescription>
>         <modbusInterfaceSelection>TCPIP</modbusInterfaceSelection>
>         <modbusTcp>
>           <port>512</port>
>           <address>192.168.1.155</address>
>           <slaveId>0</slaveId>
>         </modbusTcp>
>         <modbusRtu>
>           <slaveAddr>10</slaveAddr>
>           <baudRateSelected>19200</baudRateSelected>
> ```
> 
> There the port is in the TCPIP part? Can it really be, that both RTU and TCP are there ?

I think it is possible that a Modbus RTU device either uses RTU over serial port _OR_ RTU over a TCP/IP gateway (RTU over TCP/IP is not the same as Modbus TCP!)

I distinguish them by checking whether the tcp address or serial port name are empty, with preference to serial.

2024-05-13 13:00 UTC, ergo-furrer commented
> I distinguish them by checking whether the tcp address or serial port name are empty, with preference to serial.

Its looks like a viable solution to me. 

It means in the EI-XML above at least `<address>` and  `<comPort>` must property placeholders.

> <modbusInterfaceDescription>
>         <modbusInterfaceSelection>TCPIP</modbusInterfaceSelection>
>         <modbusTcp>
>           <port>512</port>
>           <address>{{ip_address}}</address>
>           <slaveId>0</slaveId>
>         </modbusTcp>
>         <modbusRtu>
>           <comPort>{{com_port}}</comPort>
>           <slaveAddr>10</slaveAddr>
>           <baudRateSelected>19200</baudRateSelected>

2024-05-13 13:11 UTC, mkrebs81 commented
Thanks for the feedback.

> How many options are there? Three options:
> 
> O1) RTU with serial port O2) TCP with IP and port O3) RTU over TCP with IP and port for TCP - do the serial options really make sense here?

IMHO these are the three options that may occur in a real scenario.
Of course O3 does not need any serial options. It can be configured like O2.

2024-05-13 14:02 UTC, ergo-furrer commented
> Thanks for the feedback.
> 
> > How many options are there? Three options:
> > O1) RTU with serial port O2) TCP with IP and port O3) RTU over TCP with IP and port for TCP - do the serial options really make sense here?
> 
> IMHO these are the three options that may occur in a real scenario. Of course O3 does not need any serial options. It can be configured like O2.

I agree, from the EI-XML point of view O1 and O2 are sufficient.

2024-05-14 11:56 UTC, ergo-furrer commented
@mkrebs8 Just for your information. I am currently working on this branch too to fix the EI-XML's. Some of them do not validate anymore due to the changes. I will come back when I am finished.

2024-05-22 10:37 UTC, ArndGerns approved these changes

2024-05-22 11:13 UTC, ArndGerns submitted a review, later dismissed

2024-05-22 11:21 UTC, ergo-furrer approved these changes

2024-05-22 11:33 UTC, ergo-furrer approved these changes

2024-05-22 11:33 UTC, merged